package demo.hw.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1 2012-12-19T02:19:24.515-05:00
 * Generated source version: 2.7.1
 * 
 */
public final class HelloWorld_HelloWorldPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://server.hw.demo/", "HelloWorldService");

	private HelloWorld_HelloWorldPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = HelloWorldService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		HelloWorldService ss = new HelloWorldService(wsdlURL, SERVICE_NAME);
		HelloWorld port = ss.getHelloWorldPort();
//
//		{
//			System.out.println("Invoking getUsers...");
//			demo.hw.server.IntegerUserMap _getUsers__return = port.getUsers();
//			System.out.println("getUsers.result=" + _getUsers__return);
//
//		}
		{
			System.out.println("Invoking sayHiToUser...");
			demo.hw.server.User user = new User();
			user.setName("what the fuck");
			java.lang.String _sayHiToUser__return = port
					.sayHiToUser(user);
			System.out.println("sayHiToUser.result=" + _sayHiToUser__return);

		}
//		{
//			System.out.println("Invoking sayHi...");
//			java.lang.String _sayHi_arg0 = "";
//			java.lang.String _sayHi__return = port.sayHi(_sayHi_arg0);
//			System.out.println("sayHi.result=" + _sayHi__return);
//
//		}
        System.out.println("Users: ");
        IntegerUserMap users = port.getUsers();
        for (IdentifiedUser iUser : users.getEntry()) {
			System.err.println(iUser.getUser().getName());
		}
//        for (Map.Entry<Integer, User> e : users.getEntryusers.getEntry()()()) {
//            System.out.println("  " + e.getKey() + ": " + e.getValue().getName());
//        }
		System.exit(0);
	}

}
