package demo.hw.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2012-12-19T02:19:24.550-05:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://server.hw.demo/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.GetUsers")
    @WebMethod
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.GetUsersResponse")
    public demo.hw.server.IntegerUserMap getUsers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHiToUser")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHiToUserResponse")
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        demo.hw.server.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://server.hw.demo/", className = "demo.hw.server.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
